- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launch ec2
    ec2:
      instance_type: t2.micro
      key_name: 
      image: ami-09d95fab7fff3776c
      region: us-east-1
      group: default
      count: 1
      vpc_subnet_id: subnet-64538202
      wait: yes
      assign_public_ip: yes
